### PR TITLE
Integrating iOS Unit Testing Project

### PR DESCRIPTION
**Pull request by ibalajiarun**

### CODE REVIEW

**Comment by jasedit** [comment]
The SHA1 for MobileApp is invalid here - is this pointing to a branch that's since been deleted?

**Comment by ibalajiarun** [comment]
I dont understand. Am I doing something wrong?

**Comment by ibalajiarun** [comment]
Ok. I see. I did not push the MobileApp master first. I just did.

**Comment by jasedit** [comment]
Sorry - git jargon is dense and unintuitive, but you caught it anyways. Awaiting Travis!

**Comment by jasedit** [comment]
HomeAutomationApp does not have a valid reference to api in it's build configuration currently, according to Travis.

**Comment by ibalajiarun** [comment]
Ready to merge!

**Pull request merged**
